### ISSUE TITLE
This does not install as an R package

### ISSUE THREAD

**Issue by TomKellyGenetics** [debsin/dropClust#3]
This is a great comprehensive repository of supplementary material for your publication. However, it is not an "R package" as the publication states. This is much more difficult to install (with hardcoded directories) than a typical R package. At the moment, it is difficult to tell what the package does, let alone install or run it.

I would suggest to format (and document) this tool as an R package using `devtools` and `roxygen2`. Dependancies can be listed in the DESCRIPTION file and will be installed with your package. Python and C++ codes can be called with the `reticulate` and `Rcpp` packages respectively. This would make it much more convenient for users to install and run the code. This way more people will use your tools and cite them. Please refer to this guide for how to develop R packages: [http://r-pkgs.had.co.nz/](http://r-pkgs.had.co.nz/)

**Comment by debsin** [comment]
Fixed.
