### ISSUE TITLE
Error in Tutorial

### ISSUE THREAD

**Issue by turhancan97** [debsin/dropClust#6]
While doing the tutorial when I run this code 'ScatterPlot (plot_data, title = "Clusters")', I got the following error.

Error in (function (classes, fdef, mtable):
   'unable to find an inherited method for function' reducedDims 'for signature ‘" data.frame ""'.

 What should I do?

**Comment by omkarchandra** [comment]
I am getting the same error. 

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘reducedDims’ for signature ‘"data.frame"’

**Comment by namratabhattacharya** [comment]
I am getting the same error.

Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘reducedDims’ for signature ‘"data.frame"’
